/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import CSDL.tbKhachHang;
import CSDL.tbSach;
import Models.clsKhachHang;
import Models.clsSach;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import static java.util.Calendar.DAY_OF_YEAR;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class frmChothue extends javax.swing.JFrame {

    /**
     * Creates new form frmChothue
     */
    public frmChothue() {
        initComponents();
        
        Date ngay;
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis); 
        txtFormartNgaythue.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHantra = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFormartNgaytra = new javax.swing.JTextField();
        txtFormartNgaythue = new javax.swing.JFormattedTextField();
        txtFormartHantra = new javax.swing.JFormattedTextField();
        txtTensach = new javax.swing.JTextField();
        btnSaveThue = new javax.swing.JButton();
        txtTennguoithue = new javax.swing.JTextField();
        rb_10ngay = new javax.swing.JRadioButton();
        rb_20ngay = new javax.swing.JRadioButton();
        rb_30ngay = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNguoithue = new javax.swing.JTable();
        txtTukhoaNguoithue = new javax.swing.JTextField();
        btnTimkiemnguoithue = new javax.swing.JButton();
        btnThemnguoidung = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSachthue = new javax.swing.JTable();
        txtTukhoaSach = new javax.swing.JTextField();
        btnTimkiemdausach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cho thuê sách");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cho thuê");

        jLabel3.setText("Sách thuê");

        jLabel2.setText("Người thuê");

        jLabel4.setText("Ngày thuê ");

        jLabel5.setText("Hạn trả ");

        jLabel6.setText("Ngày trả");

        txtFormartNgaytra.setText("Chưa trả");
        txtFormartNgaytra.setEnabled(false);

        txtFormartNgaythue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFormartNgaythue.setEnabled(false);

        txtFormartHantra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFormartHantra.setEnabled(false);

        txtTensach.setEnabled(false);

        btnSaveThue.setText("Thêm");

        txtTennguoithue.setEnabled(false);

        buttonGroupHantra.add(rb_10ngay);
        rb_10ngay.setText("10 ngày");
        rb_10ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_10ngayActionPerformed(evt);
            }
        });

        buttonGroupHantra.add(rb_20ngay);
        rb_20ngay.setText("20 ngày");
        rb_20ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_20ngayActionPerformed(evt);
            }
        });

        buttonGroupHantra.add(rb_30ngay);
        rb_30ngay.setText("30 ngày");
        rb_30ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_30ngayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnSaveThue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_10ngay)
                                .addGap(31, 31, 31)
                                .addComponent(rb_20ngay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_30ngay))
                            .addComponent(txtFormartNgaytra, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txtFormartHantra, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txtFormartNgaythue, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txtTennguoithue))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTennguoithue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormartNgaythue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFormartHantra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_10ngay)
                    .addComponent(rb_20ngay)
                    .addComponent(rb_30ngay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormartNgaytra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(63, 63, 63)
                .addComponent(btnSaveThue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jLabel7.setText("Tìm khách");

        tableNguoithue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách", "Tên khách hàng", "Điện thoại"
            }
        ));
        tableNguoithue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNguoithueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNguoithue);

        btnTimkiemnguoithue.setText("Tìm kiếm");
        btnTimkiemnguoithue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemnguoithueActionPerformed(evt);
            }
        });

        btnThemnguoidung.setText("Thêm ngay");

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Không có người dùng -->");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTukhoaNguoithue, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnTimkiemnguoithue))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemnguoidung)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTukhoaNguoithue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiemnguoithue))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemnguoidung)
                    .addComponent(jLabel9)))
        );

        jLabel8.setText("Tìm đầu sách");

        tableSachthue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "GIá tiền"
            }
        ));
        tableSachthue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSachthueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSachthue);

        btnTimkiemdausach.setText("Tìm kiếm");
        btnTimkiemdausach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemdausachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTukhoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnTimkiemdausach)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTukhoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiemdausach))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(434, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemnguoithueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemnguoithueActionPerformed
        // TODO add your handling code here:
        String tukhoa= txtTukhoaNguoithue.getText();
        if (tukhoa.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa!!");
        }
        else{
            tbKhachHang khach = new tbKhachHang();
            Vector<clsKhachHang> ds = khach.SearchKhachhang(tukhoa);
            if (ds.size()>0) {
                DefaultTableModel tb = (DefaultTableModel)tableNguoithue.getModel();
                tb.setRowCount(0);
                
                for (clsKhachHang kh : ds) {
                    tb.addRow(new Object[]{kh.getMaKH(),kh.getName(),kh.getPhone()});
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không có kết quả tìm kiếm nào!!");
            }
            
            
        }
    }//GEN-LAST:event_btnTimkiemnguoithueActionPerformed

    private void tableNguoithueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNguoithueMouseClicked
        // TODO add your handling code here:
        int row = (int)tableNguoithue.getSelectedRow();
        if (row<0) {
            
        }
        else{
            String masach = (String)tableNguoithue.getModel().getValueAt(row, 0);
            String tennguoithue = (String)tableNguoithue.getModel().getValueAt(row, 1);
            
            txtTennguoithue.setText(tennguoithue);
        }
    }//GEN-LAST:event_tableNguoithueMouseClicked

    private void tableSachthueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSachthueMouseClicked
        // TODO add your handling code here:
        int row = (int)tableSachthue.getSelectedRow();
        if (row<0) {
            
        }
        else{
            String masach = (String)tableSachthue.getModel().getValueAt(row, 0);
            String tensach = (String)tableSachthue.getModel().getValueAt(row, 1);
            
            txtTensach.setText(tensach);
        }
    }//GEN-LAST:event_tableSachthueMouseClicked

    private void btnTimkiemdausachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemdausachActionPerformed
        // TODO add your handling code here:
        String tukhoa= txtTukhoaSach.getText();
        if (tukhoa.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa!!");
        }
        else{
            tbSach sach = new tbSach();
            Vector<clsSach> ds = sach.SearchBook(tukhoa, 0, "", 0, 0);
            
            if (ds.size()>0) {
                DefaultTableModel tb = (DefaultTableModel)tableSachthue.getModel();
                tb.setRowCount(0);
                
                for (clsSach d : ds) {
                    tb.addRow(new Object[]{d.getMaSach(),d.getTenSach(),d.getGiaTien()});
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không có kết quả tìm kiếm nào!!");
            }
            
            
        }
    }//GEN-LAST:event_btnTimkiemdausachActionPerformed

    private void rb_10ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_10ngayActionPerformed
        // TODO add your handling code here:
        LocalDate date = java.time.LocalDate.now().plusDays(10);
        txtFormartHantra.setText(date.toString());
    }//GEN-LAST:event_rb_10ngayActionPerformed

    private void rb_20ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_20ngayActionPerformed
        // TODO add your handling code here:
         LocalDate date = java.time.LocalDate.now().plusDays(20);
        txtFormartHantra.setText(date.toString());
    }//GEN-LAST:event_rb_20ngayActionPerformed

    private void rb_30ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_30ngayActionPerformed
        // TODO add your handling code here:
         LocalDate date = java.time.LocalDate.now().plusDays(30);
        txtFormartHantra.setText(date.toString());
    }//GEN-LAST:event_rb_30ngayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChothue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChothue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChothue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChothue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChothue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveThue;
    private javax.swing.JButton btnThemnguoidung;
    private javax.swing.JButton btnTimkiemdausach;
    private javax.swing.JButton btnTimkiemnguoithue;
    private javax.swing.ButtonGroup buttonGroupHantra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb_10ngay;
    private javax.swing.JRadioButton rb_20ngay;
    private javax.swing.JRadioButton rb_30ngay;
    private javax.swing.JTable tableNguoithue;
    private javax.swing.JTable tableSachthue;
    private javax.swing.JFormattedTextField txtFormartHantra;
    private javax.swing.JFormattedTextField txtFormartNgaythue;
    private javax.swing.JTextField txtFormartNgaytra;
    private javax.swing.JTextField txtTennguoithue;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTukhoaNguoithue;
    private javax.swing.JTextField txtTukhoaSach;
    // End of variables declaration//GEN-END:variables
}
