/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import CSDL.tbUsers;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class frmEditPass extends javax.swing.JFrame {
    
    public static String _oldpass;
    public static int _id;
    /**
     * Creates new form frmEditPass
     */
    public frmEditPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JTextField();
        btnSaveEditPass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelOldPassErr = new javax.swing.JLabel();
        labelNewPassErr = new javax.swing.JLabel();
        labelReNewPassErr = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        txtReNewPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi mật khẩu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu cũ :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới :");

        txtOldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOldPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldPassKeyReleased(evt);
            }
        });

        btnSaveEditPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveEditPass.setForeground(new java.awt.Color(0, 204, 0));
        btnSaveEditPass.setText("Lưu thay đổi");
        btnSaveEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditPassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu :");

        labelOldPassErr.setForeground(new java.awt.Color(255, 0, 0));

        labelNewPassErr.setForeground(new java.awt.Color(255, 0, 0));

        labelReNewPassErr.setForeground(new java.awt.Color(255, 0, 0));

        txtReNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReNewPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOldPass)
                            .addComponent(labelOldPassErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNewPassErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNewPass)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSaveEditPass, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addGap(145, 145, 145))
                            .addComponent(labelReNewPassErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReNewPass))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOldPassErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNewPassErr, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelReNewPassErr)
                .addGap(30, 30, 30)
                .addComponent(btnSaveEditPass)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPassKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtOldPassKeyPressed

    private void txtOldPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPassKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtOldPassKeyReleased

    private void btnSaveEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditPassActionPerformed
        // TODO add your handling code here:
        String old_Pass = txtOldPass.getText();
        String new_Pass = txtNewPass.getText();
        String re_new_Pass = txtReNewPass.getText();
        if (old_Pass.equals("")) {
            labelOldPassErr.setText("Chưa nhập mật khẩu cũ!");
        }
        if (new_Pass.equals("")) {
            labelNewPassErr.setText("Chưa nhập mật khẩu mới!");
        }
         if (re_new_Pass.equals("")) {
            labelReNewPassErr.setText("Chưa nhập lại mật khẩu mới!");
        }

        if (!old_Pass.equals("") &&  !new_Pass.equals("") && !re_new_Pass.equals("")){
            if (old_Pass.equals(_oldpass)) {
                if (new_Pass.equals(re_new_Pass)) {
                    tbUsers u = new tbUsers();
                    boolean kq = u.UpdatePassUsers(_id ,new_Pass);
                    if (kq == true) {
                        JOptionPane.showMessageDialog(null, "Cập nhật thành công!!");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Cập nhật không thành công!!");
                    }
                }
                
            }
            else{
                labelOldPassErr.setText("Mật khẩu của bạn không chính xác!!");
            }
           

        }
    }//GEN-LAST:event_btnSaveEditPassActionPerformed

    private void txtReNewPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReNewPassKeyReleased
        // TODO add your handling code here:
         String new_Pass = txtNewPass.getText();
        String re_new_Pass = txtReNewPass.getText();
        if (!new_Pass.equals(re_new_Pass)) {
           labelReNewPassErr.setText("Mật khẩu mới không khớp !!");
        }
        else{
            labelReNewPassErr.setText("");
        }
    }//GEN-LAST:event_txtReNewPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveEditPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNewPassErr;
    private javax.swing.JLabel labelOldPassErr;
    private javax.swing.JLabel labelReNewPassErr;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtOldPass;
    private javax.swing.JTextField txtReNewPass;
    // End of variables declaration//GEN-END:variables
}
